### ISSUE TITLE
Absolute beginners

### ISSUE THREAD

**Issue by brianteeman** [akeeba/vagrant#2]
After installing vagrant you need to open a terminal window and run the following two commands to start vagrant

`$ vagrant init hashicorp/precise32`
`$ vagrant up`

Then you can install the two vagrant plugins

**Comment by brianteeman** [comment]
Second stupid question - after doing above and installing the plugins 
where am I supposed to put the files from this repo

**Comment by nikosdion** [comment]
First question: No. You do not need run vagrant init and vagrant up. This will create a new Vagrant box per its documentation.

Second question: Put the file anywhere you like, e.g. `~/mybox`. Then you need to go there and run vagrant up from *inside* that directory, e.g.
```bash
cd ~/mybox
vagrant up
```

The Vagrantfile in that directory is read by Vagrant and its instructions followed to create a box. You can then use all vagrant commands from inside that directory. See http://vagrant.up for information.

**Comment by brianteeman** [comment]
So when do you run the two scripts

**Comment by brianteeman** [comment]
If I want to use php 5.3.10 instead of the last release is it enough to
just change the d/l in the config.

Seems to make more sense to me to test against the lowest supported version.

Sorry for the beginner questions
On 6 Jan 2015 12:49, brian@teeman.net wrote:

So when do you run the two scripts
On 6 Jan 2015 12:28, "Nicholas K. Dionysopoulos" <notifications@github.com>
wrote:

First question: No. You do not need run vagrant init and vagrant up. This
will create a new Vagrant box per its documentation.

Second question: Put the file anywhere you like, e.g. ~/mybox. Then you
need to go there and run vagrant up from *inside* that directory, e.g.

cd ~/mybox
vagrant up

The Vagrantfile in that directory is read by Vagrant and its instructions
followed to create a box. You can then use all vagrant commands from inside
that directory. See http://vagrant.up for information.

—
Reply to this email directly or view it on GitHub
<https://github.com/akeeba/vagrant/issues/2#issuecomment-68859364>.

**Comment by nikosdion** [comment]
Please read the documentation at Vagrant's website.

When you run vagrant up the Vagrantfile is read and a new VM is created (you can actually see it in Virtualbox). vagrant up looks for Vagrantfile in the current working directory. That's why you need to be inside the directory with the checked out repository files when doing that.

As for the setup, it has to take place BEFORE creating the VM.

So:
• Check out the repository
• Run vagrant up
• Wait for 40-70 minutes to finish building the machine

You can connect to the VM via SSH using vagrant ssh. You can also connect by SFTP with hostname vagrant.up username vagrant password vagrant. Sites are inside the /var/www directory.

Each directory inside the /var/www directory can be accessed through FOUR subdomains. Let's say you have the directory dev3 (a pre-populated development J! 3 site):
• dev3.vagrant53.up  –  Running on PHP 5.3
• dev3.vagrant54.up  –  Running on PHP 5.4
• dev3.vagrant55.up  –  Running on PHP 5.5
• dev3.vagrant56.up  –  Running on PHP 5.6
It is the same site, the same files, the same database, just a different PHP FastCGI executable. So you can test your site against ALL four versions of PHP at once.

If you want to replace PHP 5.3.28 with 5.3.10 you need to edit the config.yaml file BEFORE running vagrant up for the first time inside the directory containing this repo. If you have already run vagrant up, tough. You'll have to first do a vagrant destroy, then edit the config.yaml (make sure you give it the correct URL to PHP 5.3.10 download under the php53 key) and run vagrant up again, waiting another 40 to 70 minutes.

Actually, there is a way to reprovision PHP 5.3. I'll try to recite it from memory as I'm working on the iPad due to the power outage... First you will need to delete vagrant/download/*php53* and then edit config.yaml. Afterwards run vagrant provision and sit back while Vagrant re-runs the provisioning script. This SHOULD allow you to replace PHP 5.3 after having already created the VM. That's how I developed the VM to the best of my recollection without being able to look at the files.

Good luck!=

**Comment by brianteeman** [comment]
Thanks - a task for after I finish the en-GB stuff

On 6 January 2015 at 13:35, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> Please read the documentation at Vagrant's website.
>
> When you run vagrant up the Vagrantfile is read and a new VM is created
> (you can actually see it in Virtualbox). vagrant up looks for Vagrantfile
> in the current working directory. That's why you need to be inside the
> directory with the checked out repository files when doing that.
>
> As for the setup, it has to take place BEFORE creating the VM.
>
> So:
> • Check out the repository
> • Run vagrant up
> • Wait for 40-70 minutes to finish building the machine
>
> You can connect to the VM via SSH using vagrant ssh. You can also connect
> by SFTP with hostname vagrant.up username vagrant password vagrant. Sites
> are inside the /var/www directory.
>
> Each directory inside the /var/www directory can be accessed through FOUR
> subdomains. Let's say you have the directory dev3 (a pre-populated
> development J! 3 site):
> • dev3.vagrant53.up – Running on PHP 5.3
> • dev3.vagrant54.up – Running on PHP 5.4
> • dev3.vagrant55.up – Running on PHP 5.5
> • dev3.vagrant56.up – Running on PHP 5.6
> It is the same site, the same files, the same database, just a different
> PHP FastCGI executable. So you can test your site against ALL four versions
> of PHP at once.
>
> If you want to replace PHP 5.3.28 with 5.3.10 you need to edit the
> config.yaml file BEFORE running vagrant up for the first time inside the
> directory containing this repo. If you have already run vagrant up, tough.
> You'll have to first do a vagrant destroy, then edit the config.yaml (make
> sure you give it the correct URL to PHP 5.3.10 download under the php53
> key) and run vagrant up again, waiting another 40 to 70 minutes.
>
> Actually, there is a way to reprovision PHP 5.3. I'll try to recite it
> from memory as I'm working on the iPad due to the power outage... First you
> will need to delete vagrant/download/*php53* and then edit config.yaml.
> Afterwards run vagrant provision and sit back while Vagrant re-runs the
> provisioning script. This SHOULD allow you to replace PHP 5.3 after having
> already created the VM. That's how I developed the VM to the best of my
> recollection without being able to look at the files.
>
> Good luck!=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akeeba/vagrant/issues/2#issuecomment-68865455>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by N6REJ** [comment]
wait... i'm totally lost... I want to put this on a USB so all my dev stuff is portable and I don't have to reboot... so whats step 1 and 2 please?

**Comment by nikosdion** [comment]
@N6REJ You can't. Vagrant installs on your computer. As far as I know you can't install it on a USB stick because of its dependencies.
